### ISSUE TITLE
English revolution causes game to crash

### ISSUE THREAD

**Issue by predek97** [Pergame35/Divergences#60]

**Comment by DMvers** [comment]
I found the error, it's in Ameriga events.txt , event 775424, where the Beornians try to send units to England. It can be fixed by commenting out the following lines, like so:

	#sub_unit = { type = artillery value = current }
	#sub_unit = { type = dragoon value = current }
	#sub_unit = { type = regular value = current }
	#sub_unit = { type = regular value = current }
	#sub_unit = { type = regular value = current }

I've included a fixed file as well
[Ameriga events.txt](https://github.com/Pergame35/Divergences/files/3033620/Ameriga.events.txt)

**Comment by kyle-simon** [comment]
Is it truly all of those lines? It seems like artillery and dragoons are well defined, it's just the event references the PDM unit "Regular" rather than the vanilla/HPM unit "Infantry"

**Comment by DMvers** [comment]
Good point, I'll look into it.

**Comment by DMvers** [comment]
> Is it truly all of those lines? It seems like artillery and dragoons are well defined, it's just the event references the PDM unit "Regular" rather than the vanilla/HPM unit "Infantry"

You're right, the crash is prevented by just changing regular to infantry. The units spawned are still a little bugged though: They're immovable and display as consisting of 100k each. Both issues are resolved when the units are merged ingame. I'm not sure how the AI handles this, but it is quite confusing to a player.
